### ISSUE TITLE
Development procedure for toolboxes

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-toolboxes#18]
It's not clear for me who is responsible for updating each toolbox and better to define a lead editor for each toolbox so that we can avoid a duplicate job. I can update the face and vein toolboxes because I originally drafted them.   

It may be better to define procedure to update the toolbox so that each toolbox can be developed in the same manner and avoid divergence among toolboxes. For example, in case of face toolbox, we can define the following procedure:
1. update each attack in cPP-toolboxes/2D_Face_Toolbox/attacks
1. update the general introduction and tables under cPP-toolboxes/2D_Face_Toolbox
1. update the cPP-toolboxes/toolbox.adoc that is common to all toolboxes

We can discuss this at Singapore.

**Comment by woodbe** [comment]
@woodbe will propose a folder structure with what docs we should have an how the toolbox should look
