### ISSUE TITLE
Attack Potential

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-toolboxes#20]
Research attack potential and determine level at which attacks are considered in scope for this PP-Module.

**Comment by woodbe** [comment]
During the CCUF meeting we discussed looking at what FIDO does and how that aligns with CC attack potential (I'm only using the public information found [here](https://fidoalliance.org/specs/biometric/requirements/#TriagePAD)). 

FIDO looks at 3 levels, A B C, but only requires that A and B be tested today (there is ongoing discussion about strengthening these requirements right now since there have been several certifications, based on what has now been seen).

These roughly break down to attacks of "No rating" (A) and "Basic" (B).

Copied from the FIDO document for A and B:

> **Level A**
> 
> Level A attacks are quite simple to carry out and require relatively little time, expertise, or equipment. Biometric characteristics under attack are quite easy to obtain (e.g. face image from social media, fingerprint from the device and reused directly).
> 
> 1. Elapsed time: <=one day
> 2. Expertise: Layman
> 3. Equipment: Standard
> 4. Access to biometric characteristics: Immediate, easy
> 
> **Level B**
> 
> Level B attacks require more time, expertise and equipment. Additionally, the difficulty to acquire the biometric characteristic is higher (e.g., stolen fingerprint image, high quality video of a person’s face).
> 
> 1. Elapsed time: <=one week
> 2. Expertise: Proficient
> 3. Equipment: Standard, Specialized
> 4. Access to biometric characteristics: Moderate
> 
> If at least one of these characteristics reaches the levels listed above, the attack is categorized as Level B.

Testing then means picking 6 Level A and 4 Level B (basically the lab gets to pick them, not the vendor) and they then need to pass the test. Note that they are requiring 10 PAIs vs 3, so maybe our consideration would be more types, but with the fewer PAI (i.e. more breadth of coverage instead of depth?).

Following the attack potential calculations from their lists, it would mean testing would be resistant to "Basic" attacks and susceptible to "Enhanced-Basic", if we followed along with this thinking.

The assumption here is that Knowledge of the TOE = 0 as it is only public knowledge that is used in the attack.

**Comment by woodbe** [comment]
So the proposal would be to limit to attacks that would have a score of 13 or less at this time for any attack scenario. While we can certainly create or lists attacks that are higher, they would not be considered in scope at this point.

**Comment by woodbe** [comment]
Next step will be to review the toolbox tests and add the Attack Potential calculations and then review.

Attacks considered to be Moderate (or higher) will be moved to a separate folder for future consideration.

**Comment by n-kai** [comment]
OK, I will update the vein toolbox based on your direction next week.

**Comment by woodbe** [comment]
November 21 call agreed to continue with the use of Basic resistance, and Basic-Enhance susceptibility.
