### ISSUE TITLE
[NEW MODALITY] 

### ISSUE THREAD

**Issue by Tylorjohnson40** [biometricITC/cPP-toolboxes#69]
**Be aware that adding a new modality will take at least 6 months to complete.**

For more information about the overall timeline and process, see https://github.com/biometricITC/Administration/blob/master/Toolbox_Updates.adoc.

**Requesting Organization:**
Provide contact information regarding the request.

**Status:**
If your issue arises from a currently active CC evaluation then please tick the ‘On-going certification’ box, submit the completed request through your Certification/Validation Body (CB), and update the 'Certification deadline dates' field. 

_Note that you should not be in evaluation already if you want to add a new modality on your timeline for completion._

[ ] On-going certification
[ ] Preparatory/Other

**Certification Deadline Dates:**
If your product is in an on-going CC effort please include any scheme deadlines above.

**Documentation:**
The following documentation should be ready to submit to the BIO-iTC to begin review:
- Modality Overview
- Modality Inventory
- Modality References
- Modality Verification List
- Attacks (including attack potential calculations)

Any existing modality can be used as a template for the information required.

**Rationale:**
Provide a rationale for why this modality should be added (such as use in market, demand by customers who use certified products, etc.).

**Comment by woodbe** [comment]
Closing as there is no requested modality information here. Can be re-opened if needed by submitter.
